minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@formo/analytics"
  - postcss@8.5.18
overrides:
  postcss@<8.5.18: ^8.5.18
blockExoticSubdeps: true
allowBuilds:
  bufferutil: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
